# Generated by Django 4.1.5 on 2023-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='last_name',
        ),
        migrations.AddField(
            model_name='members',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
