# Generated by Django 4.1.5 on 2023-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_members_last_name_members_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
