# Generated by Django 4.1.5 on 2023-03-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_members_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Mentee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='Mentor',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
