# Generated by Django 4.1.5 on 2023-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_members_mentee_members_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Username',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
