# Generated by Django 4.1.5 on 2023-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_members_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Mentoremail',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
