# Generated by Django 4.1.5 on 2023-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_members_end_date_members_reason_members_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
