# Generated by Django 4.1.5 on 2023-03-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_members_end_date_alter_members_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='req_sent',
            field=models.BooleanField(default=False),
        ),
    ]
