# Generated by Django 4.1.5 on 2023-04-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_members_user_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='members',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='members',
            name='start_date',
        ),
    ]
