# Generated by Django 4.1.5 on 2023-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_remove_members_req_sent_leave_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='members',
            name='n_approved',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
